import {
  Zap,
  DollarSign,
  Clock,
  Cpu,
  MemoryStick,
  Gauge,
  Lightbulb,
  CheckCircle2,
  AlertTriangle,
  Info,
  Target,
  Layers,
  GitBranch,
  Scale,
  Shield,
  Sparkles,
  ListChecks,
  HelpCircle,
  TrendingUp,
  TrendingDown,
  Wrench,
  Database,
  Server,
  Rocket,
  type LucideIcon,
} from "lucide-react";
import type { CheatIconName } from "@/lib/cheatsheet-schema";

/** The only file that imports icon components from lucide-react — keeps the icon surface bounded. */
export const cheatIcons: Record<CheatIconName, LucideIcon> = {
  zap: Zap,
  "dollar-sign": DollarSign,
  clock: Clock,
  cpu: Cpu,
  "memory-stick": MemoryStick,
  gauge: Gauge,
  lightbulb: Lightbulb,
  "check-circle-2": CheckCircle2,
  "alert-triangle": AlertTriangle,
  info: Info,
  target: Target,
  layers: Layers,
  "git-branch": GitBranch,
  scale: Scale,
  shield: Shield,
  sparkles: Sparkles,
  "list-checks": ListChecks,
  "help-circle": HelpCircle,
  "trending-up": TrendingUp,
  "trending-down": TrendingDown,
  wrench: Wrench,
  database: Database,
  server: Server,
  rocket: Rocket,
};
